create database codequest;
use codequest;
create table player (idPlayer int primary key not null auto_increment,
nome varchar(200),
vida int not null,
acertos int not null,
erros int not null,
pontos int not null);
describe player;
describe questoes;
create table questoes(idquestao int primary key not null,
enunciado varchar(1000) not null,
alternativa1 varchar(1000) not null,
alternativa2 varchar(1000) not null,
alternativa3 varchar(1000) not null,
alternativa4 varchar(1000) not null);
insert into questoes values
(0, "O que é Java?", "Java é uma linguagem de programação amplamente usada que permite a criação de aplicativos móveis \nnativos para dispositivos iOS.","Java é uma bebida energética popular consumida em todo o mundo.", "Java é um software de edição de fotos e imagens amplamente utilizado por profissionais de \ndesign gráfico.", "Java é uma plataforma de desenvolvimento de software usada para criar aplicativos web e desktop de\nalto desempenho."),
(1, "Qual a diferença entre Java e JavaScript?", "Java é uma linguagem de programação usada para desenvolver aplicativos de desktop e web, enquanto\nJavaScript é uma linguagem de programação usada principalmente para criar interatividade em páginas\nweb.", "Java é uma versão mais avançada de JavaScript, oferecendo recursos adicionais e maior desempenho.", "Java é uma linguagem de programação orientada a objetos, enquanto JavaScript é uma linguagem de \nprogramação baseada em scripts.", "Java é exclusivamente usado para programação back-end, enquanto JavaScript é usado para \nprogramação front-end."),
(2,"O que são classes em Java?", "Classes em Java são um tipo de pacote de software usado para agrupar várias classes relacionadas em \num único arquivo.", "Classes em Java são estruturas fundamentais que permitem a criação de objetos e definem seus atributos\n e comportamentos.", "Classes em Java são utilizadas para representar métodos estáticos que podem ser chamados diretamente\n sem a necessidade de instanciar um objeto.", "Classes em Java são uma forma de agrupar variáveis e constantes relacionadas para facilitar o acesso e a\n organização do código."),
(3 ,"O que é uma exceção em Java?", "Uma exceção em Java é um recurso que permite ao programa lidar com operações matemáticas \ncomplexas, como cálculos trigonométricos e exponenciais.", "Uma exceção em Java é uma instrução especial que é usada para interromper a execução de um loop ou\n um bloco condicional.", "Uma exceção em Java é um tipo de dado primitivo que armazena valores booleanos (verdadeiro ou falso)\n e é usado para controle de fluxo do programa.", "Uma exceção em Java é um evento anormal que ocorre durante a execução de um programa e\n interrompe seu fluxo normal. Elas podem ser erros de programação, condições imprevistas ou problemas\n externos."),
(4, "Como se declara uma variável em Java?", "Para declarar uma variável em Java, você precisa especificar o tipo de dados desejado, seguido pelo nome\n da variável e, opcionalmente, um valor inicial. Por exemplo: int idade = 25;","Para declarar uma variável em Java, você precisa usar a palavra-chave \"var\" seguida pelo nome da variável\n e, opcionalmente, um valor inicial. Por exemplo: var preco = 10.99;", "Para declarar uma variável em Java, você precisa especificar o tipo de dados desejado, seguido pelo nome\n da variável e, opcionalmente, um valor inicial. Por exemplo: int idade = 25;", "Para declarar uma variável em Java, você precisa usar a palavra-chave \"let\" seguida pelo nome da variável \ne, opcionalmente, um valor inicial. Por exemplo: let contador = 0;"),
(5, "O que é o Java Virtual Machine (JVM)?", " A Java Virtual Machine (JVM) é um compilador utilizado para transformar código Java em outras \nlinguagens de programação.", " A Java Virtual Machine (JVM) é um editor de texto usado para escrever programas em Java.", "A Java Virtual Machine (JVM) é um ambiente de execução para programas escritos em linguagem Java.\nEla interpreta e executa o código Java em diferentes sistemas operacionais.", "A Java Virtual Machine (JVM) é um servidor web utilizado para hospedar sites e aplicações desenvolvidas\n em Java."),
(6, "O que é um método abstrato em Java?", "Um método abstrato em Java é um método com uma implementação específica que não pode ser \nalterada nas subclasses.", "Um método abstrato em Java é um método declarado sem implementação, fornecendo uma estrutura \npara ser implementado nas subclasses.","Um método abstrato em Java é um método que não requer uma chamada explícita e é executado \nautomaticamente.", "Um método abstrato em Java é um método que só pode ser utilizado por uma única classe e não pode \nser herdado."),
(7, "Qual a diferença entre classe abstrata e interface?", "Uma classe abstrata em Java só pode ser estendida por uma única classe, enquanto uma interface pode\n ser implementada por várias classes.", "Uma classe abstrata em Java define um contrato para as subclasses, enquanto uma interface define um \nconjunto de métodos que uma classe deve implementar.", "Uma classe abstrata em Java só pode conter métodos abstratos, enquanto uma interface pode conter \ntanto métodos abstratos quanto métodos com implementações.", "Uma classe abstrata em Java pode fornecer implementações de métodos, enquanto uma interface não \npode."),
(8, "O que é uma coleção em Java?", "Uma coleção em Java é uma estrutura de dados que permite armazenar e manipular grupos de objetos \nde forma organizada e eficiente.", "Uma coleção em Java é um tipo de variável que armazena um único valor numérico, como um inteiro ou \num ponto flutuante.", "Uma coleção em Java é uma biblioteca de gráficos e recursos visuais usada para criar interfaces de usuário.", "Uma coleção em Java é uma função especial que retorna o resultado de uma expressão matemática \ncomplexa."),
(9, "O que é o polimorfismo em Java?", "O polimorfismo em Java é uma técnica para ocultar a implementação interna de um objeto, tornando-o\n acessível apenas por meio de métodos públicos.", "O polimorfismo em Java é uma forma de criar diferentes instâncias de uma classe com diferentes\n conjuntos de atributos e métodos.", "O polimorfismo em Java permite que um objeto possa ser referenciado por diferentes tipos de classes, \npossibilitando o uso de métodos com a mesma assinatura, mas com comportamentos diferentes.", "O polimorfismo em Java é uma técnica para alocar automaticamente memória para objetos e liberá-la\n quando não são mais necessários."),
(10, "O que são pacotes em Java?", "Pacotes em Java são tipos especiais de variáveis que armazenam conjuntos de valores relacionados.", "Pacotes em Java são mecanismos de organização e agrupamento de classes relacionadas, ajudando a \nevitar conflitos de nomes e facilitando a reutilização de código.", "Pacotes em Java são coleções de métodos pré-definidos que podem ser usados em diferentes partes de\n um programa.", "Pacotes em Java são arquivos de configuração que contêm informações sobre a estrutura e o \ncomportamento de um aplicativo."),
(11, "O que é uma classe interna em Java?", "Uma classe interna em Java é uma classe definida dentro de outra classe, permitindo uma relação de \ncomposição entre as classes.", "Uma classe interna em Java é uma classe que só pode ser acessada a partir de métodos estáticos de\n outra classe.", "Uma classe interna em Java é uma classe que possui apenas métodos estáticos e não pode ser instanciada.","Uma classe interna em Java é uma classe que não pode ter atributos e só pode ter métodos abstratos."),
(12, "O que é um construtor em Java?", "Um construtor em Java é um método especial utilizado para criar e inicializar objetos de uma classe.", "Um construtor em Java é uma variável que armazena valores numéricos, como inteiros e decimais.", "Um construtor em Java é um tipo de estrutura de controle usada para repetir um bloco de código várias \nvezes.", "Um construtor em Java é uma palavra-chave usada para definir as condições de execução de um bloco\n de código."),
(13, "Paradigma de programação não suportado em Java?", "Programação Orientada a Objetos.", "Programação Funcional.", "Programação Estruturada", "Programação Declarativa"),
(14, "Qual dos seguintes não é um tipo primitivo em Java?", "int.", "float.","String.", "boolean."),
(15, "Como funcionam os threads em Java?", "Os threads em Java são uma forma de armazenar e manipular conjuntos de valores relacionados.", "Os threads em Java permitem que um programa execute várias tarefas simultaneamente, dividindo-as em\n unidades menores e executando-as concorrentemente.", "Os threads em Java são uma funcionalidade que permite a comunicação entre diferentes aplicativos Java.", "Os threads em Java são uma técnica de compressão de arquivos para reduzir o tamanho de dados \narmazenados em disco."),
(16, "O que é uma anotação em Java?", "Uma anotação em Java é uma estrutura de controle que permite a execução repetitiva de um bloco de\n código.", "Uma anotação em Java é uma forma de fornecer metadados adicionais para o código, permitindo que\n você adicione informações ou instruções especiais sem alterar a lógica do programa.", "Uma anotação em Java é um tipo de variável que armazena valores constantes e imutáveis.", "Uma anotação em Java é uma palavra-chave usada para definir as restrições de acesso a um método ou\n classe."),
(17, "Qual a diferença entre StringBuilder e StringBuffer?", "A diferença entre um StringBuilder e um StringBuffer em Java é que o StringBuilder é thread-safe, \nenquanto o StringBuffer não é.", "A diferença entre um StringBuilder e um StringBuffer em Java é que o StringBuilder é uma classe imutável,\n enquanto o StringBuffer permite a modificação direta de seus valores.", "A diferença entre um StringBuilder e um StringBuffer em Java é que o StringBuilder permite operações de\nconcatenação de strings mais eficientes, enquanto o StringBuffer é mais adequado para ambientes \nmultithread.", "A diferença entre um StringBuilder e um StringBuffer em Java é que o StringBuilder é mais lento em \ntermos de desempenho em comparação com o StringBuffer."),
(18, "O que é o Javadoc em Java?", "O Javadoc em Java é uma ferramenta que permite gerar automaticamente documentação a partir de \ncomentários em código-fonte, fornecendo informações detalhadas sobre classes, métodos, parâmetros \ne retornos.", "O Javadoc em Java é uma biblioteca de gráficos e recursos visuais usada para criar interfaces de usuário.", "O Javadoc em Java é um recurso que ajuda a depurar e detectar erros em tempo de execução no código Java.", "O Javadoc em Java é uma palavra-chave usada para indicar blocos de código que não devem ser incluídos\n na compilação final do programa."),
(19, "Como funciona o garbage collector em Java?", "O garbage collector em Java é um recurso que permite que um programa interaja com o sistema \noperacional e acesse recursos externos.", "O garbage collector em Java é uma ferramenta que otimiza o desempenho do programa, reduzindo o \ntempo de execução e o consumo de recursos.", "O garbage collector em Java é uma palavra-chave usada para indicar que um objeto não deve ser \ncoletado pelo coletor de lixo.", "O garbage collector em Java é responsável por gerenciar a memória do programa, identificando e \ncoletando automaticamente os objetos que não estão mais em uso, liberando a memória ocupada por \neles."),
(20, "O que é o JDBC em Java?", "O JDBC em Java é uma biblioteca gráfica usada para criar interfaces de usuário interativas em aplicativos\n Java.",  "O JDBC em Java é uma API que permite a conexão e interação com bancos de dados relacionais, \npermitindo que os programas Java executem consultas, atualizações e outras operações de banco de \ndados.", "O JDBC em Java é um mecanismo para executar instruções de controle de fluxo, como loops e decisões \ncondicionais, em programas Java.", "O JDBC em Java é uma palavra-chave usada para definir as restrições de acesso a uma classe ou método."),
(21, "Como lidar com exceções em Java?", "Para lidar com exceções em Java, você pode ignorar completamente as exceções e permitir que o \nprograma pare de executar caso ocorra um erro.", "Para lidar com exceções em Java, você pode usar a palavra-chave \"finally\" para garantir que determinadas \nações sejam executadas independentemente de ocorrer ou não uma exceção.","Para lidar com exceções em Java, você pode usar apenas blocos try sem catch, deixando as exceções\n serem propagadas para níveis superiores do programa.", "Para lidar com exceções em Java, você pode utilizar blocos try-catch para capturar e tratar exceções \nespecíficas que podem ocorrer durante a execução do programa."),
(22, "Como funciona a serialização em Java?", "A serialização em Java é um mecanismo que otimiza o desempenho do programa, reduzindo o tempo \nde execução e o consumo de recursos.", "A serialização em Java é uma técnica que permite a execução paralela de tarefas em um programa, \naumentando a eficiência e o aproveitamento de recursos.", "A serialização em Java é um processo que permite converter objetos em uma sequência de bytes, \ntornando-os aptos para armazenamento ou transmissão, e posteriormente reconstruí-los em sua \nforma original.", "A serialização em Java é uma palavra-chave usada para indicar que um método ou classe não pode ser\n serializado."),
(23, "Qual é a função do operador ++ em Java? ", "Incrementar o valor de uma variável em 1.", "Realizar uma operação lógica de ou bit a bit.", "Subtrair o valor de uma variável por 1.", "Dividir o valor de uma variável por 2."),
(24, "A interface não permite duplicatas entre seu conteúdo é conhecida como:", "collection. ", "set. ", "queue. ", "list."),
(25, "O que é um wrapper class em Java? ", "Uma classe que empacota objetos em uma coleção.", "Uma classe que define métodos para manipular arquivos. ", "Uma classe que define uma interface para implementar herança múltipla.", "Uma classe que fornece um invólucro para tipos primitivos."),
(26, "O que é uma exceção unchecked em Java? ", "Uma exceção que ocorre durante a compilação.", "Uma exceção que ocorre quando um erro de sintaxe é encontrado. ", "Uma exceção que não precisa ser declarada ou tratada. ", "Uma exceção que é verificada em tempo de execução."),
(27, "Qual é a diferença entre == e equals() em Java? ", "== compara se dois objetos são idênticos em memória, enquanto equals() compara seus conteúdos. ", "== compara se dois objetos são iguais, enquanto equals() verifica a igualdade de seus conteúdos.", "== compara se dois objetos têm o mesmo tipo, enquanto equals() compara seus valores. ", "== compara se dois objetos têm a mesma referência, enquanto equals() compara seus campos."),
(28, " Em relação a StringBuilder, assinale a afirmativa correta.", "A classe StringBuilder fornece oito construtores.", "StringBuilders não são seguros para thread.", "O método length garante que um StringBuilder tenha pelo menos a capacidade especificada.", "Se a capacidade de um StringBuilder for excedida, há um estouro de buffer; pois a capacidade não se\n expande para acomodar mais caracteres."),
(29, "A camada __ é uma interface comum a todos os frameworks __ como o __.", "JVM / ORM / Hibernate", "JVM / ORM / OpenJDK", "JPA / ORM / Hibernate", "JPA / DBA / OpenJDK"),
(30, "Conversão de Double para String:", "String y = (double) x", "String y = String.valueOf(x)", "String y = Double.parseDouble(x)", "String y = x.getBytes()"),
(31, "Acerca da linguagem Java, assinale a alternativa correta.", "Ela aceita herança múltipla.", "É uma linguagem totalmente orientada a objetos.", "Não possibilita sobrescrever métodos.", "É possível realizar sobrecarga dos seus métodos.")
;
drop table questoes;
